// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AppStart(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['AppStart'](arg1, arg2, arg3, arg4);
}

export function AppStop() {
  return window['go']['main']['App']['AppStop']();
}

export function CheckAppStop() {
  return window['go']['main']['App']['CheckAppStop']();
}

export function GetClientsList() {
  return window['go']['main']['App']['GetClientsList']();
}

export function ReadClientsMsg() {
  return window['go']['main']['App']['ReadClientsMsg']();
}

export function ReadRemoteMsg() {
  return window['go']['main']['App']['ReadRemoteMsg']();
}
