// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AppStart(arg1:string,arg2:string,arg3:string,arg4:string):Promise<string>;

export function AppStop():Promise<void>;

export function CheckAppStop():Promise<boolean>;

export function GetClientsList():Promise<string>;

export function ReadClientsMsg():Promise<string>;

export function ReadRemoteMsg():Promise<string>;
